/*

Lisa Stephens, completed 6/18/2014
The final sum asked for in the problem definition is 4613732

Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

// Initialize global vars
var maxValue = 4000000;
var sumOfEvens = 0;

// Calculate the Fibonacci terms
// The first two terms are by definition 1 and 2
var term1 = 1;
var term2 = 2;
var newTerm;
sumOfEvens = 2;

// Calculate Fibonacci terms and update the running sumation of even values through the maxValue
while ((term1 + term2) <= maxValue) {
	// Start calculating the subsequent Fibonacci terms
	newTerm = term1 + term2;
	// If the new term is even, add it to the running sum sumOfEvens
	if (newTerm%2 === 0) {
		sumOfEvens += newTerm;
	};
	// Shift the terms to calculate the next one
	term1 = term2;
	term2 = newTerm;
}
console.log(sumOfEvens);