
# Lisa Stephens, completed 6//2014
# The final sum asked for in the problem definition is 4613732

# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By 
# starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four 
# million, find the sum of the even-valued terms.

max_range = 4000000
first_number = 1
second_number = 2
sum = 0

while first_number <= max_range
	if first_number.even?

		sum = sum + first_number 
		
	end

	new_term = first_number + second_number 
	first_number = second_number
	second_number = new_term
	
end
puts sum.to_s